### ISSUE TITLE
Missing support for cmake

### ISSUE THREAD

**Issue by CarloWood** [kfsone/imguiwrap#12]
I am having problems with integrating this library into my project.
If cmake is 100% supported, it should work seamless with my gitache project; but it doesn't.

Now gitache isn't relevant here; that does just the standard things expected for cmake; I am just mentioning it to make clear that this is a well established, automated, standard process; which doesn't work with imguiwrap ;).

The problems I run into are:

 ```
 Could not find a package configuration file provided by "imguiwrap" with
  any of the following names:

    imguiwrapConfig.cmake
    imguiwrap-config.cmake
```

And the fact that nothing got "installed".

When listing the files in the install prefix of a gitache project, I expect to see something like:

```
>ls /opt/gitache/libcwd_r/49222d132e2085669a45e519a8165087bfbe40eb818eb0743f5f7caf4a89a683/
DONE  include/  lib/  share/
```

with installed headers in include, the libraries in lib etc.
(Most notably, 'lib' contains (apart from the library itself):
```
lib/cmake/libcwd_r/libcwd_rConfigVersion.cmake
lib/cmake/libcwd_r/libcwd_rConfig.cmake
lib/cmake/libcwd_r/libcwd_rTargets.cmake
lib/cmake/libcwd_r/libcwd_rTargets-release.cmake
lib/pkgconfig/libcwd_r.pc
```

For imguiwrap I end up with:

```
>ls /opt/gitache/imguiwrap/0d4482cb3cc895fda9ade4fa0a5452f208bcc226fd07e7c60f0c10c52816f54d
DONE
```

a completely empty directory.

Obviously this doesn't allow my project to find anything - no headers and no library.

**Comment by kfsone** [comment]
Ah - that's because it's implemented for either vendoring/embedding or use via [Fetch_Content](https://cmake.org/cmake/help/latest/module/FetchContent.html), as opposed to installing as a standalone package (https://github.com/kfsone/imguiwrap#integration-with-your-cmakelists-based-project).

**Comment by CarloWood** [comment]
So, imguiwrap does not have an install target? That's basically what I was saying :-/

**Comment by kfsone** [comment]
It's not something I envisage as a distributable, only build from source. I believe the license is permissive enough that anyone who wants to use it can just drop the source in to their own code and throw away the examples/etc.

I'm happy to support anyone who wants to facilitate making it installable, but it honestly didn't occur to me that anyone might use but the non-header portion in earnest: it has main() in it.

I'm happy to maintain an install target if you want to contribute, or be supportive of it if you want to fork.
