### ISSUE TITLE
Building on a system with 'glew' installed results in link errors

### ISSUE THREAD

**Issue by kfsone** [kfsone/imguiwrap#6]
Let to its own devices, imgui will attempt to detect the opengl loader:

https://github.com/ocornut/imgui/blob/d9b606672ae145457d12dacdc82b82c6ce9ebd79/backends/imgui_impl_opengl3.h#L67-L86

and if 'glew' is present, it will find it before finding glfw.

Solution: Set IMGUI_IMPL_OPENGL_LOADER_GL3W ahead of time.

**Comment by zopsi** [comment]
This solution is elegant and fixes linker errors for me on ArchLinux/Ubuntu. Thanks!

**Comment by kfsone** [comment]
Thanks for the report, thanks for doing the pr - is appreciated - and thanks for the feedback.
